const WORDS_DATA = [
  {word: "abandon", phonetic: "/əˈbændən/", meaning: "vt. 放弃；遗弃", example: "He had to abandon his research due to lack of funding."},
  {word: "absorb", phonetic: "/əbˈzɔːrb/", meaning: "vt. 吸收；吸引注意力", example: "Plants absorb nutrients from the soil through their roots."},
  {word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的；n. 摘要", example: "The concept of justice is too abstract for a child to understand."},
  {word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "adj. 丰富的；充裕的", example: "The region is abundant in natural resources such as oil and gas."},
  {word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速；促进", example: "Exposure to sunlight will accelerate the growth of these plants."},
  {word: "access", phonetic: "/ˈækses/", meaning: "n. 进入；通道；使用权", example: "Students have free access to the university library's digital resources."},
  {word: "accommodate", phonetic: "/əˈkɑːmədeɪt/", meaning: "vt. 容纳；提供住宿；适应", example: "The new stadium can accommodate up to 80,000 spectators."},
  {word: "accomplish", phonetic: "/əˈkɑːmplɪʃ/", meaning: "vt. 完成；实现", example: "She accomplished her goal of running a marathon within six months."},
  {word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", meaning: "v. 积累；积聚", example: "Over the years, he accumulated a vast collection of rare books."},
  {word: "acknowledge", phonetic: "/əkˈnɑːlɪdʒ/", meaning: "vt. 承认；致谢", example: "The scientist acknowledged the contributions of her research team."},
  {word: "acquire", phonetic: "/əˈkwaɪər/", meaning: "vt. 获得；习得", example: "It takes years of practice to acquire fluency in a foreign language."},
  {word: "adapt", phonetic: "/əˈdæpt/", meaning: "v. 适应；改编", example: "Companies must adapt to changing market conditions to survive."},
  {word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "adj. 足够的；适当的", example: "The report did not provide adequate evidence to support its claims."},
  {word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "vt. 提倡；拥护 / n. 倡导者", example: "Many experts advocate reducing carbon emissions to combat climate change."},
  {word: "alternative", phonetic: "/ɔːlˈtɜːrnətɪv/", meaning: "n. 替代方案；adj. 替代的", example: "Solar energy is a promising alternative to fossil fuels."},
  {word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", meaning: "adj. 模棱两可的；含糊的", example: "The contract contains several ambiguous clauses that need clarification."},
  {word: "analyze", phonetic: "/ˈænəlaɪz/", meaning: "vt. 分析；解析", example: "Researchers analyzed the data to identify patterns in consumer behavior."},
  {word: "apparent", phonetic: "/əˈpærənt/", meaning: "adj. 明显的；表面上的", example: "It soon became apparent that the project was over budget."},
  {word: "approach", phonetic: "/əˈproʊtʃ/", meaning: "v./n. 接近；方法；途径", example: "We need a new approach to solving this complex problem."},
  {word: "appropriate", phonetic: "/əˈproʊpriət/", meaning: "adj. 适当的；合适的", example: "The company will take appropriate measures to address the safety concerns."},
  {word: "assess", phonetic: "/əˈses/", meaning: "vt. 评估；评定", example: "Teachers need to assess students' progress throughout the semester."},
  {word: "assume", phonetic: "/əˈsuːm/", meaning: "vt. 假设；承担", example: "We cannot simply assume that the current trend will continue indefinitely."},
  {word: "attribute", phonetic: "/əˈtrɪbjuːt/", meaning: "vt. 归因于 / n. 属性", example: "The success of the project can be attributed to effective teamwork."},
  {word: "available", phonetic: "/əˈveɪləbl/", meaning: "adj. 可获得的；有空的", example: "The report will be made available to the public next week."},
  {word: "barrier", phonetic: "/ˈbæriər/", meaning: "n. 障碍；壁垒", example: "Language barriers can create significant challenges in international business."},
  {word: "bias", phonetic: "/ˈbaɪəs/", meaning: "n. 偏见；倾向", example: "The study was criticized for having a selection bias in its sample."},
  {word: "capacity", phonetic: "/kəˈpæsəti/", meaning: "n. 能力；容量", example: "The human brain has an astonishing capacity for learning and adaptation."},
  {word: "circumstance", phonetic: "/ˈsɜːrkəmstæns/", meaning: "n. 环境；情况", example: "Under no circumstances should confidential information be disclosed."},
  {word: "cognitive", phonetic: "/ˈkɑːɡnətɪv/", meaning: "adj. 认知的", example: "Cognitive development in early childhood is crucial for later academic success."},
  {word: "compensate", phonetic: "/ˈkɑːmpenseɪt/", meaning: "v. 补偿；弥补", example: "The insurance company agreed to compensate the victims for their losses."},
  {word: "comprehensive", phonetic: "/ˌkɑːmprɪˈhensɪv/", meaning: "adj. 全面的；综合的", example: "The government proposed a comprehensive reform of the healthcare system."},
  {word: "concept", phonetic: "/ˈkɑːnsept/", meaning: "n. 概念；观念", example: "The concept of sustainable development has gained widespread acceptance."},
  {word: "consequence", phonetic: "/ˈkɑːnsɪkwens/", meaning: "n. 后果；结果", example: "The economic consequences of the pandemic were felt across the globe."},
  {word: "conserve", phonetic: "/kənˈsɜːrv/", meaning: "vt. 保护；节约", example: "We should all make an effort to conserve water and energy in daily life."},
  {word: "constitute", phonetic: "/ˈkɑːnstɪtuːt/", meaning: "vt. 构成；组成", example: "Women now constitute over half of the student body at the university."},
  {word: "consume", phonetic: "/kənˈsuːm/", meaning: "vt. 消费；消耗", example: "Households consume more electricity during the summer months due to air conditioning."},
  {word: "contemporary", phonetic: "/kənˈtempəreri/", meaning: "adj. 当代的；同时代的", example: "The museum features works by contemporary artists from around the world."},
  {word: "contribute", phonetic: "/kənˈtrɪbjuːt/", meaning: "v. 贡献；捐献；促成", example: "Regular exercise contributes significantly to both physical and mental health."},
  {word: "controversy", phonetic: "/ˈkɑːntrəvɜːrsi/", meaning: "n. 争议；争论", example: "The new policy has sparked considerable controversy among industry experts."},
  {word: "conventional", phonetic: "/kənˈvenʃənl/", meaning: "adj. 传统的；常规的", example: "Conventional farming methods often rely heavily on chemical fertilizers."},
  {word: "convince", phonetic: "/kənˈvɪns/", meaning: "vt. 说服；使信服", example: "The lawyer managed to convince the jury of her client's innocence."},
  {word: "corporate", phonetic: "/ˈkɔːrpərət/", meaning: "adj. 公司的；法人的", example: "The company places great emphasis on corporate social responsibility."},
  {word: "crucial", phonetic: "/ˈkruːʃl/", meaning: "adj. 关键的；至关重要的", example: "Effective communication is crucial for the success of any team project."},
  {word: "debate", phonetic: "/dɪˈbeɪt/", meaning: "n./v. 辩论；争论", example: "There is an ongoing debate about the ethics of artificial intelligence."},
  {word: "decline", phonetic: "/dɪˈklaɪn/", meaning: "v./n. 下降；衰退；婉拒", example: "The population of rural areas has been in steady decline for decades."},
  {word: "demonstrate", phonetic: "/ˈdemənstreɪt/", meaning: "vt. 证明；演示；表明", example: "The experiment clearly demonstrates the relationship between temperature and pressure."},
  {word: "derive", phonetic: "/dɪˈraɪv/", meaning: "v. 获得；源自", example: "Many English words derive from Latin and Greek roots."},
  {word: "diminish", phonetic: "/dɪˈmɪnɪʃ/", meaning: "v. 减少；削弱", example: "Over time, the effectiveness of the treatment began to diminish."},
  {word: "discipline", phonetic: "/ˈdɪsəplɪn/", meaning: "n. 纪律；学科；训练", example: "Academic discipline is essential for achieving long-term educational goals."},
  {word: "discrimination", phonetic: "/dɪˌskrɪmɪˈneɪʃn/", meaning: "n. 歧视；辨别", example: "Laws have been enacted to prevent discrimination in the workplace."},
  {word: "distinction", phonetic: "/dɪˈstɪŋkʃn/", meaning: "n. 区别；卓越", example: "There is a clear distinction between correlation and causation in research."},
  {word: "diverse", phonetic: "/daɪˈvɜːrs/", meaning: "adj. 多样的；不同的", example: "The university attracts students from diverse cultural backgrounds."},
  {word: "domestic", phonetic: "/dəˈmestɪk/", meaning: "adj. 国内的；家庭的", example: "The government has introduced policies to stimulate domestic consumption."},
  {word: "dominant", phonetic: "/ˈdɑːmɪnənt/", meaning: "adj. 主导的；占优势的", example: "English has become the dominant language of international scientific communication."},
  {word: "dramatic", phonetic: "/drəˈmætɪk/", meaning: "adj. 戏剧性的；巨大的", example: "The past decade has seen dramatic advances in medical technology."},
  {word: "eliminate", phonetic: "/ɪˈlɪmɪneɪt/", meaning: "vt. 消除；淘汰", example: "The new security measures aim to eliminate the risk of unauthorized access."},
  {word: "emerge", phonetic: "/iˈmɜːrdʒ/", meaning: "vi. 出现；浮现", example: "New evidence has emerged that could change the outcome of the trial."},
  {word: "emphasis", phonetic: "/ˈemfəsɪs/", meaning: "n. 强调；重点", example: "The company places great emphasis on innovation and quality control."},
  {word: "enable", phonetic: "/ɪˈneɪbl/", meaning: "vt. 使能够；使成为可能", example: "The scholarship enabled students from low-income families to attend college."},
  {word: "enhance", phonetic: "/ɪnˈhæns/", meaning: "vt. 增强；提高", example: "Regular reading can significantly enhance vocabulary and critical thinking skills."},
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = WORDS_DATA;
}
